### ISSUE TITLE
TASKING: KORBOULI - AR

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/SDCM#10]
AREA: KORBOULI
TASK: AR
RESPONSIBLE:  

@132nd-Entropy ? Are you able to create a target scenario for this area?

I have placed some MLRS that can be either the "main" target, or a High Value Target of oppertunity.
@132nd-Entropy: you mentioned in the discussion about the TRMT that you had several ideas for using MOOSE, patrolling units etc?

Maybe make this as a logistical hub, with some patrolling vehicles, and a firing position for MLRS (High Value Targets?

**Comment by 132nd-Entropy** [comment]
Hi @132ndNeck sorry for late reply. Yes, I'd be happy to take this on! Before I get at it, a little more input is requested regarding the design. 
For example, we could make three table of say  1. A-A units, 2.mobile armor 3.  high value targets
The AR is generated de-novo by randomly choosing from the 3 tables and placing them also randomly with given constraints. For example, it could be made that at any given time, only one SAM is active and on a semi-random location so it will always cover some of the range, but not all, forcing flights to fly and plan accordingly. 
Targets could be patrolling or moving, or static, its all possible (if I figure out how, but thats the fun of it).

**Comment by 132ndNeck** [comment]
@132nd-Entropy 
Excellent. That sounds like a very good idea, and those options sounds very good for keeping the mission dynamic!

**Comment by 132nd-Entropy** [comment]
this from my perspective is done and should be ready for play testing. Please feel free to change the templates as you wish (you can add/remove units or change their types, just need to keep the group name the same for the script to work). Also, the zones can be modified at will, as long as the name doesnt change. 
I close this for now, it can be reopened if needed
