### ISSUE TITLE
TASKING: ONI - AR

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/SDCM#11]
AREA: ONI
TASK: AR
RESPONSIBLE: Neck  + @132nd-Entropy 

@132nd-Entropy I have made (and flew now on Sunday) the AR tasking at ONI. This is a great area for AR missions. Could you assist me with setting up the same "template" as you have done in the AR tasking at Korbouli?  You dont need to delete anything that is there, but if you could add in the same stuff as down in Kourbuli it would be great!  (Or explain me how to do it, if I can just copy/paste stuff without knowing Moose)

I will finetune and adjust the units and zones once I have the templates in places.

**Comment by 132nd-Entropy** [comment]
on it!

**Comment by 132nd-Entropy** [comment]
Tasking Ar_Oni completed
