### ISSUE TITLE
TASKING: KASHURI - AR

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/SDCM#12]
AREA: KASHURI
TASK: AR
RESPONSIBLE: Neck + @132nd-Entropy 

@132nd-Entropy I have made an AR tasking at KASHURI. Could you assist me with setting up the same "template" as you have done in the AR tasking at Korbouli?  You dont need to delete anything that is there, but if you could add in the same stuff as down in Kourbuli it would be great!  (Or explain me how to do it, if I can just copy/paste stuff without knowing Moose)

I will finetune and adjust the units and zones once I have the templates in places.

**Comment by 132nd-Entropy** [comment]
perfect, will do

**Comment by 132nd-Entropy** [comment]
this is completed
