### ISSUE TITLE
TASKING: TSKHINVALI - AI

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/SDCM#13]
AREA: TSKHINVALI
TASK: AI
RESPONSIBLE: Neck + @132nd-Entropy 

@132nd-Entropy I have made an AI tasking at TSKHINVALI. Could you assist me with setting up the same "template" as you have done in the AR tasking at Korbouli?  You dont need to delete anything that is there, but if you could add in the same stuff as down in Kourbuli it would be great!  (Or explain me how to do it, if I can just copy/paste stuff without knowing Moose)

I will finetune and adjust the units and zones once I have the templates in places.

**Comment by 132nd-Entropy** [comment]
sure!

**Comment by 132nd-Entropy** [comment]
tasking is completed. please review/modify the unit compositions and feel free to change the waypoints defining the zones. 
The tasking can be edited freely with the following exceptions: no groups must be renamed, the hidden units should not change as they are needed in the background
