### ISSUE TITLE
Fix Tankers+AWACS - Autostart

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/SDCM#4]
Fix current tanker+ AWACS logic to use the Moose logic/script in order to make sure that we always have tanker+ AWACS.

**Comment by theendsofinvention** [comment]
The logic is currently being re-implemented in the @132nd-vWing/trmt , and will be ported over here as soon as it's done.

**Comment by 132ndNeck** [comment]
@132nd-etcher Excellent!

**Comment by theendsofinvention** [comment]
@132nd-Entropy is this already implemented in the SDCM ?

**Comment by 132nd-Entropy** [comment]
no not yet

**Comment by theendsofinvention** [comment]
On my todo list!
