### ISSUE TITLE
Create Dynamic CSAR tasking

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/SDCM#5]
Create a dynamic CSAR tasking, like in the training mission, but now also with red forces approaching the crash site.

Maybe have different types of CSAR scenarios?
1. With enemy forces approaching (a non permissive environment, in enemy territory)
2. Without enemy forces (more permissive environment, if it is possible to decide an area where it can happen)
3. With or without injured personell, so that the rescue helicopter need to take the pilot directly to a role 2 or role 3 hospital?
4. Other ideas?

Should be a way for gamemaster to enable the CSAR tasking, or another way of starting it on command per the event host's request of what he want that specific event to include.

**Comment by 132ndNeck** [comment]
@132nd-Entropy @132nd-etcher Are one of you able to support with setting up a Dynamic CSAR tasking similar that is in the TRMT?

**Comment by 132nd-Entropy** [comment]
sure, I can port it over no problem!

**Comment by 132nd-Entropy** [comment]
Dynamic CSAR tasking is in the mission now. This is a first template, and can easily be changed and reconfigured. Here is how it works:

1. There is a F10 option to activate the crashsite. The location of the crashsite will be randomly choosen amongst the zones named SAR1, SAR2, SAR3, etc. for the initial testing, I only added 3 possible zones, more can be added at any locations you like. 

2. Once the crashsite is activated, the following will happen: 
   a) an AI A10C will crash at the location given and produce smoke and wreck.
   b) a CTLD-capable MANPAD unit will be spawned that can be used as 'JTAC', he can drop smoke and 
       get picked up by any transport helo
   c) the downed pilot will activate a radio beacon, that transport pilots can home in to using CTLD. 

3. Additional option: F10 to request smoke mark (if there is no player acting as JTAC)
4. Additional option: Spawn hostiles
   a) those 'hostiles' are  blue units and will drive towards the crashsite. At some distance, they will open 
       up but target not on the pilot but close to him without killing him
   b) one of the hostile groups is in fact a transporter, once he gets close, he will disembark infantry that 
        shoot close to the pilot
  c) note: the 'hostiles' are templare groups named SARenemy1-5 they can be modified at will, but dont change the name

5. Additional option: Dispatch AI helicopter
   a) if no Mi8 player is available, an AI helo can be dispatched (currently parked close to FARP London)
   b) once activated, he will start up, find his way towards the crashsite, pickup the pilot and fly back to 
    FARP London

**Comment by 132ndNeck** [comment]
1: Sounds very good. 3 is probably good enough to start with, as we will likely not use this on every mission.
2. Nice!
3. Very good.
4. Are there any reason why they are blue units? If possible, set them to red, so they also could engage the air assets coming into the target area to pick up the survivor?
5. I vote against removing/not using this feature. If we dont have a MI-8 player, I suggest we drop doing CSAR, as you can not coordinate with a AI helicopter.

**Comment by 132nd-Entropy** [comment]
4 no, they can be changed to red with one click. my only concern was they would kill the downed pilot instantly with the AI's perfect ability to sport/hit everything. 

5. yeah sure it can be taken out, np, I just ported it over since it was there already in the TRMT

**Comment by 132nd-Entropy** [comment]
ok its solved. The CSAR hostiles are RED now, and their ROE is set to RETURN FIRE, so they wont kill the pilot, yet will shoot at players if they get engaged. 
Also the option to call in the AI huey was removed. I close this for now as I consider it a working version
